### ISSUE TITLE
This is an invalid model. Error: the graph is not acyclic.

### ISSUE THREAD

**Issue by WanchaoYao** [TexasInstruments/edgeai-tidl-tools#11]
When converting onnx model, I got below error.

Running runtimes graphviz - /home/wanchaoyao/Code/TexasInstruments/edgeai-tidl-tools/tidl_tools/tidl_graphVisualiser_runtimes.out custom-artifacts/onnx/onenet/allowedNode.txt custom-artifacts/onnx/onenet/tempDir/graphvizInfo.txt custom-artifacts/onnx/onenet/tempDir/runtimes_visualization.svg
Traceback (most recent call last):
  File "test.py", line 74, in <module>
    sess = rt.InferenceSession(onnx_model_path, providers=EP_list, provider_options=[compile_options, {}], sess_options=so)
  File "/home/wanchaoyao/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/wanchaoyao/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 315, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: the graph is not acyclic.

You can see the svg file in attachment. I think it is acutually acyclic..
![runtimes_visualization](https://user-images.githubusercontent.com/8121751/152969104-51dc7427-c11f-4bdb-a295-96dd8397ff9f.svg)
.

**Comment by kumardesappan** [comment]
Hi,
Is this model working fine with CPU only mode (that is EP_list = ['CPUExecutionProvider'])? If yes, Would it be possible to share the model used here for re-producing the issue

**Comment by WanchaoYao** [comment]
> Hi, Is this model working fine with CPU only mode (that is EP_list = ['CPUExecutionProvider'])? If yes, Would it be possible to share the model used here for re-producing the issue

Yes, it works fine with CPU only mode. How to share the model with you?

**Comment by kumardesappan** [comment]
You can either attach here or share via google drive or some other cloud storage

**Comment by WanchaoYao** [comment]
> You can either attach here or share via google drive or some other cloud storage

I've sent an email to your gmail address. And I've uploaded onnx model, model conversion code, calibration image to google dirve. You can get google drive share link in the email. Besied, the SDK version is 08_01_00_07.

**Comment by kumardesappan** [comment]
> > You can either attach here or share via google drive or some other cloud storage
> 
> I've sent an email to your gmail address. And I've uploaded onnx model, model conversion code, calibration image to google dirve. You can get google drive share link in the email. Besides, the SDK version is 08_01_00_07.

Did not receive any email yet.

**Comment by WanchaoYao** [comment]
> > > You can either attach here or share via google drive or some other cloud storage
> > 
> > 
> > I've sent an email to your gmail address. And I've uploaded onnx model, model conversion code, calibration image to google dirve. You can get google drive share link in the email. Besides, the SDK version is 08_01_00_07.
> 
> Did not receive any email yet.

I sent a email to your gmail address [kumar.adk@gmail.com](mailto:kumar.adk@gmail.com).
The share link is https://drive.google.com/file/d/1J3YjyTV5owGR65N2z--phPgjhMXVe2BR/view?usp=sharing

**Comment by anandp09** [comment]
Hi @WanchaoYao 
This model is resulting in error because TIDL Execution Provider for ONNX RT supports only 16 subgraphs delegation to TIDL. In this case, number of subgraphs is too large resulting in issue.

Support for constant multiplication as in this network is being added as part of the upcoming release, and will be available soon. I see most of the Div operators here are dividing by 1, is it possible to remove these or convert these to multiply operators in your network? The network should work fine then.

**Comment by WanchaoYao** [comment]
> Hi @WanchaoYao This model is resulting in error because TIDL Execution Provider for ONNX RT supports only 16 subgraphs delegation to TIDL. In this case, number of subgraphs is too large resulting in issue.
> 
> Support for constant multiplication as in this network is being added as part of the upcoming release, and will be available soon. I see most of the Div operators here are dividing by 1, is it possible to remove these or convert these to multiply operators in your network? The network should work fine then.

Thanks for your reply! Now I understand the problem. In fact, I did doubt the large number of subgraphs would cause problems. But the error message seems irrelevant. The uploaded model is only the backbone and neck part extracted for testing conversion. The parameters are not trained. Finally, thanks for your great advice of modification and I'm looking forward to the upcoming release.

**Comment by kasheravaibhav14** [comment]
Hi @anandp09 , 
I am having the same issue. I am trying to export a custom model to onnx using tidl backend. I have attached the logs here.
[logs-east-compile.txt](https://github.com/TexasInstruments/edgeai-tidl-tools/files/12789379/logs-east-compile.txt)
