### ISSUE TITLE
segmentation fault (core dumped) - substitute string tidl_net_ not found

### ISSUE THREAD

**Issue by WanchaoYao** [TexasInstruments/edgeai-tidl-tools#12]
When converting model, I got the following error:
------------------ Network Compiler Traces -----------------------------
successful Memory allocation
substitute string tidl_net_ not found
INFORMATION: [TIDL_ResizeLayer] Upsample_54 Any resize ratio which is power of 2 and greater than 4 will be placed by combination of 4x4 resize layer and 2x2 resize layer. For example a 8x8 resize will be replaced by 4x4 resize followed by 2x2 resize.
INFORMATION: [TIDL_ResizeLayer] Upsample_58 Any resize ratio which is power of 2 and greater than 4 will be placed by combination of 4x4 resize layer and 2x2 resize layer. For example a 8x8 resize will be replaced by 4x4 resize followed by 2x2 resize.
INFORMATION: [TIDL_ResizeLayer] Upsample_62 Any resize ratio which is power of 2 and greater than 4 will be placed by combination of 4x4 resize layer and 2x2 resize layer. For example a 8x8 resize will be replaced by 4x4 resize followed by 2x2 resize.
****************************************************
**          3 WARNINGS          0 ERRORS          **
****************************************************
[1]    17435 segmentation fault (core dumped)  python test.py

And I searched one related post:
https://e2e.ti.com/support/processors-group/processors/f/processors-forum/986167/perfsim-tool-is-stopped-with-segmentationfault

I want to know if the error is caused by Upsample? So I can change my model architecture.
Besides, the Upsample comes from FPN. So I want to know how you solve FPN conversion?

**Comment by kumardesappan** [comment]
These are warning and you can ignore them
