### ISSUE TITLE
OSError: /home/.../edgeai-tidl-tools/tidl_tools/tidl_model_import_tflite.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hfw6310** [TexasInstruments/edgeai-tidl-tools#13]
OSError: /home/.../edgeai-tidl-tools/tidl_tools/tidl_model_import_tflite.so: cannot open shared object file: No such file or directory

After the whole project is compiled, as the following figure shows, there is no folder tidl_tools in my project. could you please tell me how to address this problem?
![图片1](https://user-images.githubusercontent.com/38710029/156327369-958f0267-19e3-458f-9fb3-e3055f22f49b.png)

**Comment by hfw6310** [comment]
errors above occured when I ran the "./scripts/run_python_examples.sh" on the linux PC

**Comment by hfw6310** [comment]
Errors above occured when I ran the "./scripts/run_python_examples.sh" on one linux PC

**Comment by anandp09** [comment]
@hfw6310 
Did you run the setup.sh script?

git clone https://github.com/TexasInstruments/edgeai-tidl-tools.git
cd edgeai-tidl-tools
source ./setup.sh

**Comment by hfw6310** [comment]
> @hfw6310 Is this issue resolved?

yes, thank you, it is due to the mismatch of python version which should be 3.6 .    Can you please tell me how to solve this issue at https://github.com/TexasInstruments/edgeai-yolov5/issues/8 ? we want to run our trained yolov5 model for object detection on J721e EVM based on the vision_apps object detection demo at https://downloads.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/latest/exports/docs/vision_apps/docs/user_guide/group_apps_dl_demos_app_tidl_od.html#autotoc_md70 .

**Comment by anandp09** [comment]
@hfw6310  Let me close this thread in that case and let's continue the discussion in the above mentioned thread.
