### ISSUE TITLE
write range to tidl model

### ISSUE THREAD

**Issue by Jzz24** [TexasInstruments/edgeai-tidl-tools#19]
How to write custom quantization parameters to ti dl model, is there any tool?

**Comment by kumardesappan** [comment]
Current tools do not accept custom quantization parameters for any generic model, Howerevr user can train the model with QAT using below in this case the ranges are directly used from model and computed by the TIDL tools again
https://github.com/TexasInstruments/edgeai/blob/master/readme_models.md#model-quantization
