### ISSUE TITLE
TIDL-RT for object detection task.

### ISSUE THREAD

**Issue by lcc815** [TexasInstruments/edgeai-tidl-tools#21]
Hi~

According to [this README](https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/examples/tidlrt_cpp#readme), one can easily reproduce the tidl-rt-based classification demo.
However, now i am trying to deploy an object detection model, which encountered some problem.
I have not changed the [cpp file](https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/examples/tidlrt_cpp/classification.cpp), and build it as the README says. Significantly, i use a od model to replace a classification model like
`./bin/Release/tidlrt_clasification -i test_data/airshow.jpg  -f model-artifacts/od-ort-ssd-lite_mobilenetv2_fpn -d 1`
It gives only little error information:
```
Model Files names : model-artifacts/od-ort-ssd-lite_mobilenetv2_fpn/boxeslabels_tidl_net.bin,model-artifacts/od-ort-ssd-lite_mobilenetv2_fpn/boxeslabels_tidl_io_1.bin
 0.0s:  VX_ZONE_INIT:Enabled
 0.26s:  VX_ZONE_ERROR:Enabled
 0.29s:  VX_ZONE_WARNING:Enabled
 0.1057s:  VX_ZONE_INIT:[tivxInit:178] Initialization Done !!!
invoked 
Segmentation fault (core dumped)
```
So wired! Could any please offer any cues about this error?

**Comment by kumardesappan** [comment]
Please refer the latest documentation here
https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/examples/osrt_cpp/README.md#run

**Comment by lcc815** [comment]
> Please refer the latest documentation here https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/examples/osrt_cpp/README.md#run

Thanks for your kind reply. But the  latest documentation is about osrt, and I want to use tidl-rt instead.
