### ISSUE TITLE
when TIDL complier will be updated based on onnx opset=13?

### ISSUE THREAD

**Issue by leadcain** [TexasInstruments/edgeai-tidl-tools#22]
Hi.

I'm a DL engineer, use the TDA4VM chip for automotive.

We choses TDA4VM for plexible DSP H/W architecture.

But, TIDL support layers and operation based on onnx opset=11 have so many limitations.

We can't fully develop Deep Learning algorithms because of the limiatations.

So, We wait for SDK8.2 update, but it was not.

When do you update TIDL SDK based on ONNX opset=13?

If it will be updated, almost DL algorithm develpers using TIDL welcome.

We really eagerly look forward to update.

Thanks.

**Comment by kumardesappan** [comment]
Hi,
We are in the process of planning our future release to update opset version. We will update the detail in our standard roadmap document when it is finalized.
Would it be possible for you to share the list of operators that you are using from opest 13 definition, this would help us to plan the migration.

**Comment by kumardesappan** [comment]
I believe all the operators are supported in opest 11 also, Any particular reason to use opest 13
