### ISSUE TITLE
How to use the softmax(dim=1)?

### ISSUE THREAD

**Issue by smilecode-github** [TexasInstruments/edgeai-tidl-tools#23]
Hello.

I am making a segmentation model using softmax(dim=1).

I compiled my model using edgeai-tidl-tools on PC.

But, I found softmax(dim=1) layer is not supported. 

Because softmax is only supported in [1, 1, 1, N], so it cannot be used for dim=1.

How to use the softmax(dim=1)?

Also, How to check softmax(dim=1) in compile using edgeai-tidl-tools on PC?

**Comment by suyali** [comment]
@smilecode-github   Have you solved this problem?
