### ISSUE TITLE
Model Compilation Problem

### ISSUE THREAD

**Issue by omer-boyraz** [TexasInstruments/edgeai-tidl-tools#24]
when i run "python3 onnxrt_ep.py -c" code to create modelartifacts folder. The code runtime stands and waits and not finish.

terminal output expects as follows:
***************************************************************************************************************************************
sefau18@ubuntu:~/edgeai-tidl-tools/examples/osrt_python/ort$ python3 onnxrt_ep.py -c
Available execution providers :  ['TIDLExecutionProvider', 'TIDLCompilationProvider', 'CPUExecutionProvider']

Running 1 Models - ['best']

Running_Model :  best  

TIDL Meta PipeLine (Proto) File  : /home/sefau18/edgeai-tidl-tools/models/public/best.prototxt  
yolo_v3
yolo_v3
Number of OD backbone nodes = 0 
Size of odBackboneNodeIds = 0 

Preliminary subgraphs created = 0 
Final number of subgraphs created are : 0, - Offloaded Nodes - 0, Total Nodes - 1 
TIDL Meta PipeLine (Proto) File  : /home/sefau18/edgeai-tidl-tools/models/public/best.prototxt  
yolo_v3
yolo_v3
Number of OD backbone nodes = 0 
Size of odBackboneNodeIds = 0 

Preliminary subgraphs created = 0 
Final number of subgraphs created are : 0, - Offloaded Nodes - 0, Total Nodes - 1 
TIDL Meta PipeLine (Proto) File  : /home/sefau18/edgeai-tidl-tools/models/public/best.prototxt  
yolo_v3
yolo_v3
Number of OD backbone nodes = 328 
Size of odBackboneNodeIds = 328 

Preliminary subgraphs created = 1 
Final number of subgraphs created are : 1, - Offloaded Nodes - 434, Total Nodes - 434
***************************************************************************************************************************************
What could be the problem?

**Comment by anandp09** [comment]
@omer-boyraz  Which pytorch version are you using for exporting the model? It seems to be generating 3 subgraphs in the ONNX model, one actual and 2 others with dangling nodes which seems to be causing the issue.

**Comment by kumardesappan** [comment]
@omer-boyraz Is this issue still open, if yes please provide additional information as rested by @anandp09
