### ISSUE TITLE
is supported by python3.9

### ISSUE THREAD

**Issue by suyali** [TexasInstruments/edgeai-tidl-tools#27]
![image](https://user-images.githubusercontent.com/33011961/181172737-86d12481-77b7-41ff-bd22-186b66741aa5.png)

**Comment by kumardesappan** [comment]
As documented in the user guide, We support only python 3.6 for model compilation
![image](https://user-images.githubusercontent.com/20221577/184284790-951846e0-7651-4454-8d36-c66f2e2d8497.png)
