### ISSUE TITLE
Expected Model Compilation Output in Model Artifacts?

### ISSUE THREAD

**Issue by dpetersonVT23** [TexasInstruments/edgeai-tidl-tools#28]
I am compiling YOLOv5 Ti Lite .onnx and .prototxt using onnxrt_ep.py. If the model compilation is successful, what files should I expect to see in model_artifacts?

If I am compiling for the Beaglebone AI board on my Linux PC, what should I be setting device to?

**Comment by kumardesappan** [comment]
The model_artifacts shall have couple *.bin and *.txt  and few *svg files that would be used in inference.
BTW,user need not to understand these file, just need to pass the folder as input to the RT creation

**Comment by dpetersonVT23** [comment]
Sounds good thank you.
