### ISSUE TITLE
Testing on x86_64 to port to AARCH_64

### ISSUE THREAD

**Issue by silver2row** [TexasInstruments/edgeai-tidl-tools#35]
Hello,

Is there a way to build this repo easily? I have tried w/ building it in many, different ways, e.g. make, cmake, w/ build dirs, and w/ docker.

I am not making any headway. The https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/dockers/dependency_build files here are not working or have been moved.

Seth

P.S. I do not know if people are still interested in these libs. but I have been trying over the course of two months to build them. I have been highly unsuccessful so far. I need hints or ideas at most. Send guidance.

**Comment by fadilmohd007** [comment]
Hi,

Sorry to hear that. we appreciate the feedback.
For better understanding I would like to know few details on what exactly you are trying to experiment with, I'm unable to deduce following info from the problem statement.
1)  Which device are you trying to run the final executable ?
2)  Which runtime(python/cpp or both) you are looking forward to ?
3) Where exactly are you stuck ? is it in compilation or execution on target or PC?
4) What is the error message ?
5) Which libs are you referring to ,in the PS section?

**Comment by silver2row** [comment]
Hello,

1. BeagleBone AI-64
2. both
3. Compilation
4. All...I am having a complication building

```
git clone https://github.com/TexasInstruments/edgeai-tidl-tools.git
#export DEVICE=j7
#export DEVICE=am62
cd edgeai-tidl-tools
source ./setup.sh
```

The above ` source ./setup.sh ` command does not build the entire repo. I will get the required error output soon. Sorry I was so vague. I just did not know where to start.

Seth

**Comment by fadilmohd007** [comment]
Hello,

Currently we are not supporting BeagleBone in edgeai-tidl-tools. But as a work around I can suggest you the following

- Compile the model for J721E
- Copy the model-artifacts folder generated to the BeagleBone board 
- Run the execution part 

Regarding the setup script:

- It is intended only to download necessary python and other packages required for model compilation. 
     - Run `export DEVICE=j7`  before sourcing the setup.sh .
- For model compilation you can refer https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/examples/osrt_python#model-compilation-on-pc

**Comment by silver2row** [comment]
Hello,

Thank you for your time. I will try it again.

Seth
