### ISSUE TITLE
How can I compile model having two outputs?

### ISSUE THREAD

**Issue by smilecode-github** [TexasInstruments/edgeai-tidl-tools#36]
Hi

I want to compile a model having two branches.

The model architecture is below:

Backbone -> FPN -> output1(object detection branch, using NMS), output2 (segmentation branch)

To compile the model, I need to set the values as in the example below.

For example,

![스크린샷, 2022-10-12 18-18-55](https://user-images.githubusercontent.com/59694658/195303589-494706f2-50fa-4549-a23b-e928bb0c4caa.png)

But, I want to compile different model types such as 'od', and 'seg' at the same time.

Also, Object detection must use the NMS. but, Segmentation does not use NMS.

And, Object detection must have prototxt file. but, Segmentation does not have it.

Compiling the od and seg models separately works without any problems. But we want to share the backbone and get 2 different branch results.

I look forward to your reply.

Thank you.

**Comment by yongguanjiangshan** [comment]
hello, do you solve the problem? Could you share me how to convert the multi-task model? Looking forward for your reply, thank you!!!
