### ISSUE TITLE
edgeai-tidl-tools-master/tidl_tools/tidl_model_import_onnx.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JamesWang007** [TexasInstruments/edgeai-tidl-tools#4]
Hi,

I was following the step and running "python onnxrt_eq.py -c" under ...../examples/osrt_python/ort. 
It pops up the error:
"Error -   $/home/user/edgeai-tidl-tools-master/tidl_tools/tidl_model_import_onnx.so: cannot open shared object file: No such file or directory"

However, I have tidl_model_import_onnx.so under $TIDL_TOOLS_PATH.
Can anyone help to check the problem?

**Comment by JamesWang007** [comment]
I solved it by adding "export $TIDL_TOOLS_PATH=/home/user/edgeai-tidl-tools-master/tidl_tools" to the last line of my ~/.bashrc file, and "source ~/.bashrc".

**Comment by kumardesappan** [comment]
This issue would not have occurred if the setup script was source properly with below command as this environment variable is already set in this script
source ./setup.sh
