### ISSUE TITLE
about the setup.sh?

### ISSUE THREAD

**Issue by Onehundred0906** [TexasInstruments/edgeai-tidl-tools#44]
![2022-11-21 17-26-11屏幕截图](https://user-images.githubusercontent.com/111262872/203014252-7766c82e-97b6-4405-b0f1-e0819491eec9.png)
hello, please explain the DEVICE present what? my product is TDA4VM.

**Comment by edtamarin** [comment]
If you have a TDA4VM device, before running the setup script, you have to execute
`export DEVICE=j7`

**Comment by vtrip97** [comment]
@Onehundred0906  - On the current most releases (09_02_09_00), you need to export the SOC field, you can refer to the following table to understand (am68pa) in your case: https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master?tab=readme-ov-file#supported-devices
