### ISSUE TITLE
while loading shared libraries: libcgraph.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JamesWang007** [TexasInstruments/edgeai-tidl-tools#5]
/home/user/github/edgeai-tidl-tools-master/tidl_tools/tidl_graphVisualiser.out: error while loading shared libraries: libcgraph.so.6: cannot open shared object file: No such file or directory

when compiling and running the model, it popped up an error which says missing libcgraph.so.6. 

Can anyone help. 

The command I was running: "python3 onnxrt_ep.py -c" under the directory "examples/osrt_python/ort".

**Comment by JamesWang007** [comment]
solve it by adding "libcgraph.so.6" directory to $LD_LIBRARY_PATH

**Comment by kumardesappan** [comment]
This can be solved by installing graphviz package as mentioned in Docker file "https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/Dockerfile". Will update documentation to refer docker file in the futre for such issues
apt install -y  graphviz
