### ISSUE TITLE
How to install onnxsim?

### ISSUE THREAD

**Issue by liteonalvinchuang** [TexasInstruments/edgeai-tidl-tools#50]
How do you install onnxsim in PC emulation environment in order to run the scripts in `edgeai-tidl-tools/examples/osrt_python/advanced_examples/unit_tests_validation`? I failed to install it by running `pip3 install onnxsim`. Is there a specific version or a TI custom version of onnxsim required?

**Comment by vtrip97** [comment]
@liteonalvinchuang  - The latest setup script (09_02_09_00) installs [model-optimizer](https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/scripts/osrt_model_tools/onnx_tools/tidl-onnx-model-optimizer) through which you should pass your models for optimization and simplification
