### ISSUE TITLE
Unable to benchmark compiled models on SoC

### ISSUE THREAD

**Issue by mash2612** [TexasInstruments/edgeai-tidl-tools#51]
SoC = am68a
Tag used: 08_06_00_03

I have followed the steps mentioned in the Readme file to compile the model and generate binaries. While following the instructions to benchmark the model on SoC, I ran the following command:
cmake ../examples && make -j && cd ..

This leads to the following issue:
![image](https://user-images.githubusercontent.com/30777758/228801571-bc7b7336-e9df-47ea-b629-117b1f67b986.png)

I also noticed that the folder tidl_tools is also missing on the SoC where the file is located (checked this on x86_64 PC).

**Comment by Lsy-1997** [comment]
i got the same error, happen in "make -j", still can not fix it.

**Comment by mash2612** [comment]
@Lsy-1997 : if it helps you can have a look here: https://e2e.ti.com/support/processors-group/processors/f/processors-forum/1211663/tda4al-q1-tda4al/4601362#4601362
