### ISSUE TITLE
 operating efficiency

### ISSUE THREAD

**Issue by pengcheng001** [TexasInstruments/edgeai-tidl-tools#52]
Thank you very much. Is it more efficient to run ONNX on TDA and directly call openvx?

**Comment by vtrip97** [comment]
@pengcheng001 - the most optimal route is to use the OSRT based interfaces to compile your model & evaluate and try to completely offload your model to the DSP. Post that you can take a look at how the DSP only model can be deployed efficiently in the TIDL-RT CPP Application : https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/examples/tidlrt_cpp
