### ISSUE TITLE
Compiler's configuration parameters 

### ISSUE THREAD

**Issue by yurkovak** [TexasInstruments/edgeai-tidl-tools#56]
I found this docs page, [Configuration Parameters](https://software-dl.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/06_02_00_21/exports/docs/tidl_j7_01_01_00_10/ti_dl/docs/user_guide_html/md_tidl_naps_configinfo.htm), and I'm interested in the `MSMCSIZE_KB` parameter for TDA4VM. Could you please elaborate on how to use this config? The docs are very scarce, it seems that it should be used with one of the _edgeai-tidl-tools/tidl_tools/*.so_ files, but it's not explained which one and at which stage. 

1. Can `MSMCSIZE_KB` be configured during the python pipeline described [here](https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/docs/custom_model_evaluation.md#custom-model-evaluation)?
2. Should it be used in the compilation or inference stage? 
3. Should it be used on a host device or on the chip itself? 

Thanks in advance!

**Comment by kumardesappan** [comment]
MSMCSIZE_KB  can be set in the "edgeai-tidl-tools/tidl_tools/device_config.cfg".
It is used compilation steps and models artefacts are generated based on this compilation parameters
It is applicable for both host device or on the chip
