### ISSUE TITLE
need more document to explain example's config settings

### ISSUE THREAD

**Issue by fiefdx** [TexasInstruments/edgeai-tidl-tools#6]
there are a lot of settings in python example utils.py, and a lot of number in it, but, no document to explain what these numbers means.

**Comment by kumardesappan** [comment]
Details on all the options can be found here.
https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/examples/osrt_python/README.md#user-options-for-tflite-and-onnx-runtime

If you still notice any undocumented optioned, let us know
