### ISSUE TITLE
CPP Compiled Failed: cannot find -lonnxruntime

### ISSUE THREAD

**Issue by Lllllp93** [TexasInstruments/edgeai-tidl-tools#7]
Hi there,

I need to run my model on TDA4VM  with CPP APIs (dlr). I write a CPP script for my model,which can be built and run on PC. But that file cannot be built on TDA4, below is the output info:
 
![edgeai](https://user-images.githubusercontent.com/39562096/143802136-32a19baa-e35a-49fb-bb90-2ef6803bf7d8.jpg)

I tried to 2 ways :
1. copy the libonnxruntime.so from tidl_tools(PC sdk8.0 folder) to /usr/lib (on TDA4)
2. download tidl_tools.tar.gz in this repo and copy libonnxruntime.so to /usr/lib (on TDA4)

But cannot work, **how can I solve this problem?**

BTW, I can run my model with CPP API on TDA4VM [in this way](https://software-dl.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/08_00_00_12/exports/docs/tidl_j7_08_00_00_10/ti_dl/docs/user_guide_html/md_tidl_osr_tvm_tidl.html), but the inference time is two times slower than python API.
**so what's the difference between these two methods to run CPP API?**

**Comment by kumardesappan** [comment]
Please reefer the DLR CPP example available here to run on PC as well as VEM
https://github.com/TexasInstruments/edgeai-tidl-tools/tree/master/examples/osrt_cpp/dlr

libonnxruntime.so Is already available in EVM file system. Need not to copy specifically. The cmake rule added the required path to the link command

**Comment by Lllllp93** [comment]
But the error is 'cannot find -lonnxruntime' even if the EVM file system is correct . Or can you provide a correct verison of libonnxruntime.so and tell me where should I copy to?
