### ISSUE TITLE
Have you tested your own instructions?

### ISSUE THREAD

**Issue by provVladBurlik** [TexasInstruments/edgeai-tidl-tools#70]
- Ubuntu 22.04
- tag 09_01_01_01
Followed the instructions  - line by line and repeated the steps few times:
# PC Initial setup
sudo apt-get install libyaml-cpp-dev
git clone https://github.com/TexasInstruments/edgeai-tidl-tools.git
cd edgeai-tidl-tools
git checkout tags/09_01_01_01
export SOC=am68pa
source ./setup.sh

# PC Open new terminal
cd edgeai-tidl-tools
export SOC=am68pa
export TIDL_TOOLS_PATH=$(pwd)/tidl_tools
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TIDL_TOOLS_PATH
export ARM64_GCC_PATH=$(pwd)/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu

# PC Compile and validate examples
mkdir build && cd build
`cmake ../examples && make -j && cd ..`
source ./scripts/run_python_examples.sh
python3 ./scripts/gen_test_report.py

Here is the outcome:

osrt_cpp/post_process/CMakeFiles/post_process.dir/flags.make:10: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/Makefile2:259: osrt_cpp/post_process/CMakeFiles/post_process.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
osrt_cpp/pre_process/CMakeFiles/pre_process.dir/flags.make:10: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/Makefile2:285: osrt_cpp/pre_process/CMakeFiles/pre_process.dir/all] Error 2
osrt_cpp/utils/CMakeFiles/utils.dir/flags.make:10: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/Makefile2:311: osrt_cpp/utils/CMakeFiles/utils.dir/all] Error 2
osrt_cpp/advanced_examples/utils/CMakeFiles/utils_adv.dir/flags.make:10: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/Makefile2:424: osrt_cpp/advanced_examples/utils/CMakeFiles/utils_adv.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by verderog** [comment]
Have you tried building things with Docker?  If you modify the repo's Dockerfile (note: visit #67 because the Dockerfile doesn't exactly work as-is), you should hopefully be able to build things that way.  Not sure if this is an option for you, but doing that allowed me to build and validate things for the PC successfully.

**Comment by abhigoku10** [comment]
@provVladBurlik  where u able to solve this error ? in tried setting up this in my two systems one having gpu and non gpu one . i get this error only in the non gpu system . are you also facing things similarly

**Comment by matt-forallepsilon** [comment]
Same error for me

**Comment by vtrip97** [comment]
@provVladBurlik  - The USE_PROXY issue has been fixed as of newer releases, thanks @verderog  for pointing it out. Please refer to updated instructions for building with docker: https://github.com/TexasInstruments/edgeai-tidl-tools/blob/master/docs/advanced_setup.md
